alias bastproxy='ssh -qCnfND 8889 bast00'
alias workdesk='ssh -qCnfND 8889 workdesk'
alias chinaproxy='ssh -qCnfND 8889 chn-tfi'
alias dubproxy='ssh -qCnfND 8889 dubpr1bast'
alias akc='~/work/awseks/bin/kubectl'
alias aws-creds='make renew -C ~/work/aws-concur/resources/auth'
